# Generated by Django 4.2.1 on 2023-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribegreen',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribption',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
