# Generated by Django 4.2.1 on 2023-06-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email',)},
        ),
    ]
