# Generated by Django 4.2.1 on 2023-06-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
    ]
