# Generated by Django 4.2.1 on 2023-06-23 19:14

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0003_alter_advantagesimage_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantagesimage',
            name='image1',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image2',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image3',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image4',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image5',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='advantages/'),
        ),
    ]
