# Generated by Django 4.2.1 on 2023-06-23 19:39

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0004_alter_advantagesimage_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantagesimage',
            name='image1_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image2_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image3_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image4_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image5_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='fbimage_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image1_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image2_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image3_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image4_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image5_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fbimage',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='feedbacks/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image1',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='raiting/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image2',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='raiting/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image3',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='raiting/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image4',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='raiting/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='image5',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='raiting/'),
        ),
    ]
