# Generated by Django 4.2.1 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe',
            field=models.CharField(choices=[('None', 'None'), ('White', 'White'), ('Green', 'Green')], default='None', max_length=10),
        ),
    ]
