# Generated by Django 4.2.1 on 2023-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0005_customuser_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribe',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('White', 'White'), ('Green', 'Green')], default='None', max_length=10, null=True),
        ),
    ]
