# Generated by Django 4.2.1 on 2023-06-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0005_advantagesimage_image1_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantagesimage',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='advantagesimage',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='advantagesimage',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='advantagesimage',
            name='image4_url',
        ),
        migrations.RemoveField(
            model_name='advantagesimage',
            name='image5_url',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fbimage_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image4_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image5_url',
        ),
    ]
