# Generated by Django 4.2.1 on 2023-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0006_alter_customuser_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribe',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('white', 'white'), ('green', 'green')], default='None', max_length=10, null=True),
        ),
    ]
