# Generated by Django 4.2.1 on 2023-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0006_remove_advantagesimage_image1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantagesimage',
            name='image1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advantagesimage',
            name='image5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
