# Generated by Django 4.2.1 on 2023-06-24 03:27

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0007_advantagesimage_image1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='image5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fbimage',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='feedback/'),
        ),
    ]
