# Generated by Django 4.2.1 on 2023-06-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redforceapp', '0010_customuser_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='online',
        ),
    ]
